### ISSUE TITLE
Adversarial Patch notebook: Unable to run

### ISSUE THREAD

**Issue by chrisbodhi** [tensorflow/cleverhans#417]
Howdy,

Thanks so much for sharing your work!

When trying to reproduce an error in the Adversarial Patch notebook [related to failing to load the `cross_model_patch` object], I found that when following the instructions for running the notebook in Colaboratory [Python 2 with GPU], the notebook threw a `ResourceExhaustedError` at the "Transfer Attack (AKA Blackbox)" section. Here's a [link to the cell](https://colab.research.google.com/drive/1GmUJUHZ0lR0UqDEujr7bayDfYx_AatTq#scrollTo=iibw1L5NxVK6&line=8&uniqifier=1) in a copy of the notebook that I ran. It seems that in the notebook in the repo, this cell might not have been run -- there's no output for that cell saved. 

Any insights on how to get the notebook running would be much appreciated!

**Comment by goodfeli** [comment]
I'm not sure if this just means your machine doesn't have enough memory to run the notebook, but that might be all that's going on. @nottombrown ?

**Comment by nottombrown** [comment]
Not sure what's up with this. I just spun up a new colab with Python2 and a GPU and it worked correctly for me.

![image](https://user-images.githubusercontent.com/306655/41066517-e5c37ac4-6996-11e8-8b95-fb6ecafe605b.png)

I would try to fix it by doing the following (in order of increasing annoyingness):
```
1. Restart your colab kernel
2. Change your runtime type and then change it back
3. Reduce the BATCH_SIZE from 16 to 8
```

**Comment by goodfeli** [comment]
(feel free to re-open if this fix doesn't work)

**Comment by chrisbodhi** [comment]
I had already tried the first two suggestions, but dropping the `BATCH_SIZE` down to `8` worked like a charm -- thanks!

```
Beginning blackbox experiment with ensemble: ['resnet50', 'xception', 'inceptionv3', 'vgg16'] and target vgg19
[0] loss: 12.815981
...
[450] loss: 0.39939258
```
